server:
  port: 1112
eureka:
  instance:
    hostname: eureka-server1
  client:
    #fetch-registry: false
    #register-with-eureka: false
    service-url:
      defaultZone: http://localhost:1111/eureka/

#eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
#默认30s 改为3秒刷新一次
  server:
    response-cache-update-interval-ms: 3000
#eureka server缓存readWriteCacheMap失效时间，这个只有在这个时间过去后缓存才会失效，失效前不会更新，过期后从registry重新读取注册服务信息，registry是一个ConcurrentHashMap。
#由于启用了evict其实就用不太上改这个配置了
#默认180s
    response-cache-auto-expiration-in-seconds: 180
#启用主动失效，并且每次主动失效检测间隔为3s
    eviction-interval-timer-in-ms: 2000 #此参数暂时不起效果
    lease-expiration-duration-in-seconds: 20000 #在注册中心接收到euraka客户端最后一次续约心跳后等待的上限时间，超过改时间则提出服务。

spring:
  application:
    name: eureka-server1