server:
  port: 9002
spring:
  application:
    name: hello-service-api

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:1112/eureka/
feign:
   hystrix:
     enabled: true