server:
  port: 1113
spring:
  application:
    name: hello-service
  cloud:
    loadbalancer:
      retry:
        enabled: true #开启重试机制
endpoints:
  shutdown:
    enabled: true    #开启优雅关闭方式
management:
  security:
    enabled: false  #关闭安全认证

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

hello-service:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 2
    MaxAutoRetries: 1
eureka:
  instance:
    hostname: localhost
#服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
#注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
#默认90s
    lease-expiration-duration-in-seconds: 15
#服务刷新时间配置，每隔这个时间会主动心跳一次
#默认30s
    lease-renewal-interval-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/

