
package test.ws.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://service/", className = "service.GetUser")
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://service/", className = "service.GetUserResponse")
    public User getUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    long arg0);

    /**
     * 
     * @param userId
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "String", targetNamespace = "")
    @RequestWrapper(localName = "getName", targetNamespace = "http://service/", className = "service.GetName")
    @ResponseWrapper(localName = "getNameResponse", targetNamespace = "http://service/", className = "service.GetNameResponse")
    public String getName(
            @WebParam(name = "userId", targetNamespace = "")
                    Long userId);

}
