server:
  port: 8002
spring:
  application:
    name: jdbcTemplate

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      ctldb:
        url: jdbc:postgresql://192.168.25.132:5432/activiti
        username: pg01
        password: 123456
        driver-class-name: org.postgresql.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
         # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 'ZTM' FROM DUAL
#        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
#        通过connectionProperties开启 mergesql功能  慢sql统计
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        mindle: 1 #最小连接数
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2
      mngdb:
        url: jdbc:postgresql://192.168.25.132:5432/postgres
        username: pg01
        password: 123456
        driver-class-name: org.postgresql.Driver
        minIdle: 1
        maxActive: 2
        initialSize: 1
        timeBetweenEvictionRunsMillis: 3000
        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 'ZTM' FROM DUAL
#        validationQueryTimeout: 10000
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        maxWait: 60000
#        通过connectionProperties开启 mergesql功能  慢sql统计
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        mindle: 1 #最小连接数
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,log4j2